#!/usr/bin/env python3
"""Emit the language-neutral golden file that pins cc-history's parsing/truncation
behavior. The TypeScript port (cc-history-vscode) asserts byte-exact equality
against this file, so the two implementations can share an index.db.

Run from the repo root:  python tests/gen_golden.py
Writes: tests/fixtures/expected-entries.json
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import cc_history as cc  # noqa: E402

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "sample-session.jsonl"
OUT = Path(__file__).resolve().parent / "fixtures" / "expected-entries.json"


def fixture_entries() -> list[dict]:
    """Run the real parser over every fixture line; flatten to the indexable
    (role, kind, tool_name, text) rows, in order."""
    rows: list[dict] = []
    with FIXTURE.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            _ts, entries = cc.parse_line(obj)
            for e in entries:
                rows.append({
                    "role": e.role,
                    "kind": e.kind,
                    "tool_name": e.tool_name,
                    "text": e.text,
                })
    return rows


def truncation_cases() -> list[dict]:
    """Deterministic inputs the TS port reconstructs identically, with the exact
    byte-truncated output from the CLI's _truncate. Exercises the multibyte
    (Hebrew) boundary where the byte limit falls mid-character."""
    cases = []
    # Hebrew tool_result over 8192 bytes; a 1-byte ASCII prefix shifts the 2-byte
    # Hebrew chars so the 8192-byte boundary lands mid-character.
    c1_input = "x" + ("ש" * 5000)
    cases.append({
        "name": "hebrew_tool_result_8192_midchar",
        "build": {"prefix": "x", "char": "ש", "count": 5000},
        "limit": cc.TOOL_RESULT_MAX,
        "expected": cc._truncate(c1_input, cc.TOOL_RESULT_MAX),
    })
    # Hebrew tool_use over 4096 bytes, even (on-boundary) case.
    c2_input = "ש" * 3000
    cases.append({
        "name": "hebrew_tool_use_4096",
        "build": {"prefix": "", "char": "ש", "count": 3000},
        "limit": cc.TOOL_USE_MAX,
        "expected": cc._truncate(c2_input, cc.TOOL_USE_MAX),
    })
    # Mixed ASCII+Hebrew, no truncation (under limit) — must pass through unchanged.
    c3_input = "auth flow שלום"
    cases.append({
        "name": "under_limit_passthrough",
        "build": {"literal": c3_input},
        "limit": cc.TOOL_RESULT_MAX,
        "expected": cc._truncate(c3_input, cc.TOOL_RESULT_MAX),
    })
    return cases


def main() -> None:
    payload = {
        "_comment": "Golden contract generated by tests/gen_golden.py — do not hand-edit.",
        "fixture": FIXTURE.name,
        "limits": {"tool_use": cc.TOOL_USE_MAX, "tool_result": cc.TOOL_RESULT_MAX},
        "entries": fixture_entries(),
        "truncation": truncation_cases(),
    }
    OUT.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(payload['entries'])} entries, "
          f"{len(payload['truncation'])} truncation cases)")


if __name__ == "__main__":
    main()
